#pragma once

typedef unsigned long NAVSTATUS, *PNAVSTATUS, *LPNAVSTATUS;

#define NAV_SUCCESS(x) (((NAVSTATUS)x == 1) || ((NAVSTATUS)x >= 0x7fffffff))

#define NAV_PRIVILEGE_STATUS_FAILED				0x00
#define NAV_PRIVILEGE_STATUS_SUCCESS			0x01
#define NAV_PRIVILEGE_STATUS_NOT_ASSIGNED		0x02
#define NAV_PRIVILEGE_STATUS_ENABLE_FAILED		0x04

#define NAV_TOKEN_STATUS_FAILED					0x00
#define NAV_TOKEN_STATUS_SUCCESS				0x01
#define NAV_TOKEN_STATUS_OPEN_PROCESS_FAILED	0x02

#define NAV_CLOSE_TOKEN_STATUS_FAILED			0x00
#define NAV_CLOSE_TOKEN_STATUS_SUCCESS			0x01

#define NAV_CHECK_PRIVILEGE_STATUS_FAILED				0x00
#define NAV_CHECK_PRIVILEGE_STATUS_SUCCESS				0x01
#define NAV_CHECK_PRIVILEGE_STATUS_UNKNOWN_INFO			0x02
#define NAV_CHECK_PRIVILEGE_STATUS_UNKNOWN_LUID			0x04
#define NAV_CHECK_PRIVILEGE_STATUS_UNKNOWN_BUFFER_SIZE	0x08

#define NAV_SET_ACE_STATUS_KERNEL_OBJECT_CHANGE_FAILED	0x00
#define NAV_SET_ACE_STATUS_SUCCESS						0x01
#define NAV_SET_ACE_STATUS_UNKNOWN_BUFFER_SIZE			0x02
#define NAV_SET_ACE_STATUS_MEMORY_ALLOCATION_FAILED		0x04
#define NAV_SET_ACE_STATUS_UNKNOWN_SECURITY_DESCRIPTOR	0x08
#define NAV_SET_ACE_STATUS_DACL_CHANGE_FAILED			0x10
#define NAV_SET_ACE_STATUS_DESCRIPTOR_CHANGE_FAILED		0x20
#define NAV_SET_ACE_STATUS_RETRIEVE_DACL_FAILED			0x40